<?php

namespace Database\Seeders;

use App\Models\Produit;
use App\Models\Categorie;
use App\Models\Fournisseur;
use Illuminate\Database\Seeder;

class ProduitSeeder extends Seeder
{
    public function run(): void
    {
        // Récupérer les IDs des catégories
        $alimentaire = Categorie::where('nom', 'Produits Alimentaires')->first()->id;
        $boissons    = Categorie::where('nom', 'Boissons')->first()->id;
        $hygiene     = Categorie::where('nom', 'Hygiène & Beauté')->first()->id;
        $electronique = Categorie::where('nom', 'Électronique')->first()->id;
        $vetements   = Categorie::where('nom', 'Vêtements')->first()->id;
        $laitiers    = Categorie::where('nom', 'Produits Laitiers')->first()->id;
        $viandes     = Categorie::where('nom', 'Viandes & Poissons')->first()->id;
        $fruits      = Categorie::where('nom', 'Fruits & Légumes')->first()->id;
        $entretien   = Categorie::where('nom', 'Entretien Maison')->first()->id;

        // Récupérer les IDs des fournisseurs
        $sobemap  = Fournisseur::where('nom', 'SOBEMAP')->first()->id;
        $castel   = Fournisseur::where('nom', 'CASTEL BENIN')->first()->id;
        $prosuma  = Fournisseur::where('nom', 'PROSUMA')->first()->id;
        $agridev  = Fournisseur::where('nom', 'AGRIDEV')->first()->id;
        $electro  = Fournisseur::where('nom', 'ELECTRO BENIN')->first()->id;

        $produits = [
            // ===== ALIMENTAIRES =====
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $sobemap,
                'libelle'       => 'Riz parfumé 5kg',
                'reference'     => 'RIZ-5KG-001',
                'code_barre'    => '6001000000001',
                'unite'         => 'sac',
                'prix_achat'    => 3500,
                'prix_detail'   => 4500,
                'prix_moyen'    => 4200,
                'prix_gros'     => 3800,
                'stock_actuel'  => 150,
                'stock_minimum' => 20,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $sobemap,
                'libelle'       => 'Riz parfumé 25kg',
                'reference'     => 'RIZ-25KG-001',
                'code_barre'    => '6001000000002',
                'unite'         => 'sac',
                'prix_achat'    => 16000,
                'prix_detail'   => 20000,
                'prix_moyen'    => 18500,
                'prix_gros'     => 17000,
                'stock_actuel'  => 80,
                'stock_minimum' => 10,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $sobemap,
                'libelle'       => 'Huile végétale 1L',
                'reference'     => 'HUI-1L-001',
                'code_barre'    => '6001000000003',
                'unite'         => 'bouteille',
                'prix_achat'    => 800,
                'prix_detail'   => 1000,
                'prix_moyen'    => 950,
                'prix_gros'     => 900,
                'stock_actuel'  => 200,
                'stock_minimum' => 30,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $sobemap,
                'libelle'       => 'Huile végétale 5L',
                'reference'     => 'HUI-5L-001',
                'code_barre'    => '6001000000004',
                'unite'         => 'bidon',
                'prix_achat'    => 3800,
                'prix_detail'   => 4800,
                'prix_moyen'    => 4500,
                'prix_gros'     => 4200,
                'stock_actuel'  => 100,
                'stock_minimum' => 15,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Farine de blé 1kg',
                'reference'     => 'FAR-1KG-001',
                'code_barre'    => '6001000000005',
                'unite'         => 'paquet',
                'prix_achat'    => 450,
                'prix_detail'   => 600,
                'prix_moyen'    => 550,
                'prix_gros'     => 500,
                'stock_actuel'  => 180,
                'stock_minimum' => 30,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Sucre en poudre 1kg',
                'reference'     => 'SUC-1KG-001',
                'code_barre'    => '6001000000006',
                'unite'         => 'paquet',
                'prix_achat'    => 500,
                'prix_detail'   => 650,
                'prix_moyen'    => 600,
                'prix_gros'     => 550,
                'stock_actuel'  => 250,
                'stock_minimum' => 40,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Sel iodé 500g',
                'reference'     => 'SEL-500G-001',
                'code_barre'    => '6001000000007',
                'unite'         => 'paquet',
                'prix_achat'    => 150,
                'prix_detail'   => 250,
                'prix_moyen'    => 220,
                'prix_gros'     => 200,
                'stock_actuel'  => 300,
                'stock_minimum' => 50,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $sobemap,
                'libelle'       => 'Tomate concentrée 400g',
                'reference'     => 'TOM-400G-001',
                'code_barre'    => '6001000000008',
                'unite'         => 'boîte',
                'prix_achat'    => 350,
                'prix_detail'   => 500,
                'prix_moyen'    => 450,
                'prix_gros'     => 400,
                'stock_actuel'  => 120,
                'stock_minimum' => 20,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Pâtes spaghetti 500g',
                'reference'     => 'PAT-500G-001',
                'code_barre'    => '6001000000009',
                'unite'         => 'paquet',
                'prix_achat'    => 300,
                'prix_detail'   => 450,
                'prix_moyen'    => 400,
                'prix_gros'     => 350,
                'stock_actuel'  => 200,
                'stock_minimum' => 30,
            ],
            [
                'categorie_id'  => $alimentaire,
                'fournisseur_id' => $sobemap,
                'libelle'       => 'Sardines en conserve',
                'reference'     => 'SAR-165G-001',
                'code_barre'    => '6001000000010',
                'unite'         => 'boîte',
                'prix_achat'    => 400,
                'prix_detail'   => 600,
                'prix_moyen'    => 550,
                'prix_gros'     => 500,
                'stock_actuel'  => 5,
                'stock_minimum' => 20,
            ],

            // ===== BOISSONS =====
            [
                'categorie_id'  => $boissons,
                'fournisseur_id' => $castel,
                'libelle'       => 'Eau minérale 1.5L',
                'reference'     => 'EAU-1.5L-001',
                'code_barre'    => '6002000000001',
                'unite'         => 'bouteille',
                'prix_achat'    => 200,
                'prix_detail'   => 350,
                'prix_moyen'    => 300,
                'prix_gros'     => 250,
                'stock_actuel'  => 500,
                'stock_minimum' => 100,
            ],
            [
                'categorie_id'  => $boissons,
                'fournisseur_id' => $castel,
                'libelle'       => 'Eau minérale 0.5L',
                'reference'     => 'EAU-0.5L-001',
                'code_barre'    => '6002000000002',
                'unite'         => 'bouteille',
                'prix_achat'    => 100,
                'prix_detail'   => 200,
                'prix_moyen'    => 175,
                'prix_gros'     => 150,
                'stock_actuel'  => 800,
                'stock_minimum' => 150,
            ],
            [
                'categorie_id'  => $boissons,
                'fournisseur_id' => $castel,
                'libelle'       => 'Bière Flag 65cl',
                'reference'     => 'BIE-FLAG-001',
                'code_barre'    => '6002000000003',
                'unite'         => 'bouteille',
                'prix_achat'    => 400,
                'prix_detail'   => 600,
                'prix_moyen'    => 550,
                'prix_gros'     => 500,
                'stock_actuel'  => 300,
                'stock_minimum' => 50,
            ],
            [
                'categorie_id'  => $boissons,
                'fournisseur_id' => $castel,
                'libelle'       => 'Coca-Cola 33cl',
                'reference'     => 'SOD-COCA-001',
                'code_barre'    => '6002000000004',
                'unite'         => 'canette',
                'prix_achat'    => 300,
                'prix_detail'   => 500,
                'prix_moyen'    => 450,
                'prix_gros'     => 400,
                'stock_actuel'  => 0,
                'stock_minimum' => 50,
            ],
            [
                'categorie_id'  => $boissons,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Jus de bissap 1L',
                'reference'     => 'JUS-BIS-001',
                'code_barre'    => '6002000000005',
                'unite'         => 'bouteille',
                'prix_achat'    => 500,
                'prix_detail'   => 750,
                'prix_moyen'    => 700,
                'prix_gros'     => 650,
                'stock_actuel'  => 80,
                'stock_minimum' => 20,
            ],

            // ===== HYGIENE =====
            [
                'categorie_id'  => $hygiene,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Savon de Marseille 200g',
                'reference'     => 'SAV-MAR-001',
                'code_barre'    => '6003000000001',
                'unite'         => 'pièce',
                'prix_achat'    => 150,
                'prix_detail'   => 250,
                'prix_moyen'    => 220,
                'prix_gros'     => 200,
                'stock_actuel'  => 400,
                'stock_minimum' => 50,
            ],
            [
                'categorie_id'  => $hygiene,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Shampooing 400ml',
                'reference'     => 'SHA-400ML-001',
                'code_barre'    => '6003000000002',
                'unite'         => 'flacon',
                'prix_achat'    => 800,
                'prix_detail'   => 1200,
                'prix_moyen'    => 1100,
                'prix_gros'     => 1000,
                'stock_actuel'  => 150,
                'stock_minimum' => 20,
            ],
            [
                'categorie_id'  => $hygiene,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Dentifrice 75ml',
                'reference'     => 'DEN-75ML-001',
                'code_barre'    => '6003000000003',
                'unite'         => 'tube',
                'prix_achat'    => 500,
                'prix_detail'   => 750,
                'prix_moyen'    => 700,
                'prix_gros'     => 650,
                'stock_actuel'  => 200,
                'stock_minimum' => 30,
            ],
            [
                'categorie_id'  => $hygiene,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Déodorant roll-on',
                'reference'     => 'DEO-ROL-001',
                'code_barre'    => '6003000000004',
                'unite'         => 'pièce',
                'prix_achat'    => 700,
                'prix_detail'   => 1000,
                'prix_moyen'    => 900,
                'prix_gros'     => 850,
                'stock_actuel'  => 120,
                'stock_minimum' => 20,
            ],

            // ===== ELECTRONIQUE =====
            [
                'categorie_id'  => $electronique,
                'fournisseur_id' => $electro,
                'libelle'       => 'Chargeur téléphone USB-C',
                'reference'     => 'CHA-USBC-001',
                'code_barre'    => '6004000000001',
                'unite'         => 'pièce',
                'prix_achat'    => 1500,
                'prix_detail'   => 2500,
                'prix_moyen'    => 2200,
                'prix_gros'     => 2000,
                'stock_actuel'  => 60,
                'stock_minimum' => 10,
            ],
            [
                'categorie_id'  => $electronique,
                'fournisseur_id' => $electro,
                'libelle'       => 'Écouteurs intra-auriculaires',
                'reference'     => 'ECO-INT-001',
                'code_barre'    => '6004000000002',
                'unite'         => 'pièce',
                'prix_achat'    => 1000,
                'prix_detail'   => 1800,
                'prix_moyen'    => 1600,
                'prix_gros'     => 1400,
                'stock_actuel'  => 8,
                'stock_minimum' => 10,
            ],
            [
                'categorie_id'  => $electronique,
                'fournisseur_id' => $electro,
                'libelle'       => 'Pile AA (pack de 4)',
                'reference'     => 'PIL-AA-001',
                'code_barre'    => '6004000000003',
                'unite'         => 'pack',
                'prix_achat'    => 300,
                'prix_detail'   => 500,
                'prix_moyen'    => 450,
                'prix_gros'     => 400,
                'stock_actuel'  => 200,
                'stock_minimum' => 30,
            ],

            // ===== LAITIERS =====
            [
                'categorie_id'  => $laitiers,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Lait en poudre 400g',
                'reference'     => 'LAI-400G-001',
                'code_barre'    => '6006000000001',
                'unite'         => 'boîte',
                'prix_achat'    => 1800,
                'prix_detail'   => 2500,
                'prix_moyen'    => 2300,
                'prix_gros'     => 2100,
                'stock_actuel'  => 100,
                'stock_minimum' => 15,
            ],
            [
                'categorie_id'  => $laitiers,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Yaourt nature 500g',
                'reference'     => 'YAO-500G-001',
                'code_barre'    => '6006000000002',
                'unite'         => 'pot',
                'prix_achat'    => 400,
                'prix_detail'   => 600,
                'prix_moyen'    => 550,
                'prix_gros'     => 500,
                'stock_actuel'  => 80,
                'stock_minimum' => 15,
            ],
            [
                'categorie_id'  => $laitiers,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Beurre 250g',
                'reference'     => 'BEU-250G-001',
                'code_barre'    => '6006000000003',
                'unite'         => 'plaquette',
                'prix_achat'    => 800,
                'prix_detail'   => 1200,
                'prix_moyen'    => 1100,
                'prix_gros'     => 1000,
                'stock_actuel'  => 60,
                'stock_minimum' => 10,
            ],

            // ===== ENTRETIEN =====
            [
                'categorie_id'  => $entretien,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Lessive poudre 1kg',
                'reference'     => 'LES-1KG-001',
                'code_barre'    => '6009000000001',
                'unite'         => 'paquet',
                'prix_achat'    => 600,
                'prix_detail'   => 900,
                'prix_moyen'    => 800,
                'prix_gros'     => 700,
                'stock_actuel'  => 180,
                'stock_minimum' => 25,
            ],
            [
                'categorie_id'  => $entretien,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Eau de Javel 1L',
                'reference'     => 'JAV-1L-001',
                'code_barre'    => '6009000000002',
                'unite'         => 'bouteille',
                'prix_achat'    => 300,
                'prix_detail'   => 500,
                'prix_moyen'    => 450,
                'prix_gros'     => 400,
                'stock_actuel'  => 150,
                'stock_minimum' => 20,
            ],
            [
                'categorie_id'  => $entretien,
                'fournisseur_id' => $prosuma,
                'libelle'       => 'Liquide vaisselle 750ml',
                'reference'     => 'LIQ-750ML-001',
                'code_barre'    => '6009000000003',
                'unite'         => 'flacon',
                'prix_achat'    => 400,
                'prix_detail'   => 650,
                'prix_moyen'    => 600,
                'prix_gros'     => 550,
                'stock_actuel'  => 120,
                'stock_minimum' => 20,
            ],
        ];

        foreach ($produits as $produit) {
            Produit::updateOrCreate(
                ['reference' => $produit['reference']],
                $produit
            );
        }

        $this->command->info('✅ ' . count($produits) . ' Produits créés avec succès');
    }
}